services:
  frontend:
    build: ./cloud-computing-final-project
    ports:
      - "3000:3000"
    restart: always
  backend:
    build: ./python_backend
    volumes:
      - ./backend:/user/src/app
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
    restart: on-failure