apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ykumawat/cc-frontend
          ports:
            - containerPort: 5000
          env:
            - name: TODO_API_URL
              value: http://api.default.svc.cluster.local:5001
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer